language: ruby
rvm:
  - 2.1.2

env:
  - DB="sqlite"
  # - DB="postgresql"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
# before_script:
#   - sqlite -e "create database portfolio_test"
#   - psql -c "create database portfolio_test" -U postgres
# bundler_args: --binstubs=./bundler_stubs
