language: ruby
rvm:
- 2.1.2
addon:
  postgresql: "9.3"
env:
- DB=postgresql
before_script:
- psql -c 'create database travis_test_psql' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
deploy:
  provider: heroku
  api_key:
    secure: WaQducIHer1zs2/MhvUtt5vkCiZ6s4So/SmAz5DOiMGX/vZ9+JgFmCVRvGw0bViA0LNY/JN+hgzHzG3RvBTxu81PwNbTH/fkcIsP9h75uLowTpuWWhjJwU+EnmwynU7s1ucRts+PI1wl3kQT0qjKw4Ic+qlbZAm/CyTO91aSj7E=
  app: philip-q-nguyen
  on:
    repo: philipqnguyen/portfolio
    branch: master
  run: "rake db:migrate"
